name: Avica

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Downloading & Installing Essentials
        shell: pwsh
        run: |
          Write-Host "Downloading .bat file..."
          Invoke-WebRequest -Uri "https://gitlab.com/raposabtry/pcrdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          if (Test-Path "Downloads.bat") {
            Write-Host "File downloaded. Running Downloads.bat..."
            Start-Process -FilePath "Downloads.bat" -Wait
          } else {
            Write-Error "Failed to download Downloads.bat"
            exit 1
          }

      - name: Show Website
        shell: cmd
        run: |
          if exist show.bat (
            call show.bat
          ) else (
            echo show.bat not found.
            exit 1
          )
